CREATE TABLE system_settings
(
    id                           BIGINT PRIMARY KEY,
    store_name                   VARCHAR(160)   NOT NULL,
    logo_url                     VARCHAR(500)   NULL,
    contact_email                VARCHAR(254)   NOT NULL,
    default_currency             VARCHAR(12)    NOT NULL,
    default_language             VARCHAR(16)    NOT NULL,
    payment_credit_card_enabled  BIT            NOT NULL DEFAULT 1,
    payment_cod_enabled          BIT            NOT NULL DEFAULT 1,
    payment_stripe_enabled       BIT            NOT NULL DEFAULT 0,
    stripe_public_key            VARCHAR(255)   NULL,
    stripe_secret_encrypted      VARCHAR(1024)  NULL,
    shipping_fee                 DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    free_shipping_threshold      DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    delivery_regions_json        TEXT           NULL,
    estimated_delivery_time      VARCHAR(120)   NOT NULL,
    tax_rate                     DECIMAL(5, 2)  NOT NULL DEFAULT 0.00,
    tax_rules_json               TEXT           NULL,
    stock_threshold              INT            NOT NULL DEFAULT 10,
    low_stock_alert_enabled      BIT            NOT NULL DEFAULT 1,
    reviews_enabled              BIT            NOT NULL DEFAULT 1,
    notify_new_orders            BIT            NOT NULL DEFAULT 1,
    notify_low_stock             BIT            NOT NULL DEFAULT 1,
    notify_new_users             BIT            NOT NULL DEFAULT 1,
    password_min_length          INT            NOT NULL DEFAULT 8,
    password_require_uppercase   BIT            NOT NULL DEFAULT 1,
    password_require_number      BIT            NOT NULL DEFAULT 1,
    password_require_special     BIT            NOT NULL DEFAULT 0,
    session_timeout_minutes      INT            NOT NULL DEFAULT 30,
    max_login_attempts           INT            NOT NULL DEFAULT 5,
    jwt_expiration_minutes       INT            NOT NULL DEFAULT 15,
    created_at                   TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at                   TIMESTAMP(6)   NULL
);

INSERT INTO system_settings (id,
                             store_name,
                             logo_url,
                             contact_email,
                             default_currency,
                             default_language,
                             payment_credit_card_enabled,
                             payment_cod_enabled,
                             payment_stripe_enabled,
                             stripe_public_key,
                             stripe_secret_encrypted,
                             shipping_fee,
                             free_shipping_threshold,
                             delivery_regions_json,
                             estimated_delivery_time,
                             tax_rate,
                             tax_rules_json,
                             stock_threshold,
                             low_stock_alert_enabled,
                             reviews_enabled,
                             notify_new_orders,
                             notify_low_stock,
                             notify_new_users,
                             password_min_length,
                             password_require_uppercase,
                             password_require_number,
                             password_require_special,
                             session_timeout_minutes,
                             max_login_attempts,
                             jwt_expiration_minutes,
                             created_at,
                             updated_at)
VALUES (1,
        'Sports Hub',
        NULL,
        'admin@sportshub.local',
        'USD',
        'en',
        1,
        1,
        0,
        NULL,
        NULL,
        8.99,
        80.00,
        '["United States"]',
        '3-5 business days',
        7.00,
        '[]',
        10,
        1,
        1,
        1,
        1,
        1,
        8,
        1,
        1,
        0,
        30,
        5,
        15,
        CURRENT_TIMESTAMP(6),
        CURRENT_TIMESTAMP(6));
